### PR TITLE
Ian feature branch

### PR DESCRIPTION
**Pull request by ihoffman117**
-adds a model so that when clicking on the main image in the overview it will display only the image. 
-adds a translation effect to image thumbnails
-adds functionality to dynamically render the sizes in the size dropdown based on what is in stock for the products selected style
-fixes sensitive information being committed and pushed to github in exampleConfig.js

### CODE REVIEW

**Comment by kanderson250** [comment]
This looks great, Ian. I will merge it but have one suggestion for you to consider: your Modal off/on functions can be consolidated into a single 'toggle' function, to be used by both kinds of clicks.

**Comment by es98dame** [comment]
looks good to me.
just a quick question. In ProductSpecs.jsx, Are you planning to implement average review calculations for star ratings?

**Comment by ihoffman117** [comment]
@es98dame I do plan to actually calculate the average I just have the set number in there as a stand-in

**Comment by es98dame** [comment]
@ihoffman117 Cool. Because I need to implement it too. My first idea is to get all the ratings from 'reviews/?product_id=65632', put them in an array, add them all up, get the average and pass this to the star rating. Any other ideas?

**Pull request merged**
